import type { GlobalThemeOverrides } from "naive-ui";

export function createNaiveThemeOverrides(isDark: boolean): GlobalThemeOverrides {
  const common = {
    primaryColor: "#0ea5e9",
    primaryColorHover: "#0284c7",
    primaryColorPressed: "#0369a1",
    primaryColorSuppl: "#7dd3fc",
    successColor: "#10b981",
    warningColor: "#f97316",
    errorColor: "#ef4444",
    infoColor: "#0ea5e9",
    borderRadius: "18px",
    borderRadiusSmall: "14px",
    borderRadiusMedium: "18px",
    borderRadiusLarge: "22px",
    borderRadiusHuge: "26px",
    fontFamily:
      "\"SF Pro Display\", \"PingFang SC\", \"Microsoft YaHei\", \"Helvetica Neue\", sans-serif",
  };
  const panelColor = isDark ? "#0f172a" : "#ffffff";
  const floatingColor = isDark ? "#111c2b" : "#ffffff";
  const subtleSurface = isDark ? "rgba(30, 41, 59, 0.9)" : "rgba(255, 255, 255, 0.88)";
  const subtleSurfaceHover = isDark ? "rgba(51, 65, 85, 0.96)" : "rgba(248, 250, 252, 0.98)";
  const subtleSurfacePressed = isDark ? "rgba(71, 85, 105, 0.92)" : "rgba(241, 245, 249, 0.98)";
  const subtleSurfaceDisabled = isDark ? "rgba(30, 41, 59, 0.58)" : "rgba(241, 245, 249, 0.9)";
  const border = isDark ? "1px solid rgba(148,163,184,0.2)" : "1px solid rgba(148,163,184,0.28)";
  const borderHover = isDark ? "1px solid rgba(125,211,252,0.42)" : "1px solid rgba(59,130,246,0.35)";
  const borderFocus = isDark ? "1px solid rgba(96,165,250,0.6)" : "1px solid rgba(59,130,246,0.5)";
  const borderDisabled = isDark ? "1px solid rgba(71,85,105,0.42)" : "1px solid rgba(203,213,225,0.9)";
  const strongText = isDark ? "#f8fafc" : "#0f172a";
  const bodyText = isDark ? "#e2e8f0" : "#1e293b";
  const mutedText = isDark ? "#cbd5e1" : "#475569";
  const quietText = isDark ? "#94a3b8" : "#64748b";
  const focusRing = isDark ? "0 0 0 3px rgba(59,130,246,0.18)" : "0 0 0 3px rgba(59,130,246,0.12)";

  return {
    common: {
      ...common,
      cardColor: isDark ? "rgba(10, 18, 30, 0.82)" : "rgba(255,255,255,0.82)",
      modalColor: panelColor,
      popoverColor: floatingColor,
      bodyColor: isDark ? "#0b1420" : "#f8fafc",
      tableColor: isDark ? "#0f172a" : "#ffffff",
      dividerColor: isDark ? "rgba(148, 163, 184, 0.14)" : "rgba(15, 23, 42, 0.08)",
      borderColor: isDark ? "rgba(148, 163, 184, 0.16)" : "rgba(15, 23, 42, 0.08)",
      textColorBase: bodyText,
      textColor1: strongText,
      textColor2: mutedText,
      textColor3: quietText,
    },
    Button: {
      borderRadiusTiny: "12px",
      borderRadiusSmall: "14px",
      borderRadiusMedium: "16px",
      borderRadiusLarge: "18px",
      textColorPrimary: "#ffffff",
      textColorHoverPrimary: "#ffffff",
      textColorPressedPrimary: "#ffffff",
      textColorFocusPrimary: "#ffffff",
      colorSecondary: subtleSurface,
      colorSecondaryHover: subtleSurfaceHover,
      colorSecondaryPressed: subtleSurfacePressed,
      colorTertiary: subtleSurface,
      colorTertiaryHover: subtleSurfaceHover,
      colorTertiaryPressed: subtleSurfacePressed,
      colorQuaternary: isDark ? "rgba(15, 23, 42, 0.2)" : "rgba(255, 255, 255, 0.22)",
      colorQuaternaryHover: isDark ? "rgba(30, 41, 59, 0.42)" : "rgba(255, 255, 255, 0.34)",
      colorQuaternaryPressed: isDark ? "rgba(51, 65, 85, 0.5)" : "rgba(241, 245, 249, 0.46)",
      colorDisabled: subtleSurfaceDisabled,
      textColor: strongText,
      textColorTertiary: strongText,
      textColorHover: strongText,
      textColorPressed: strongText,
      textColorFocus: strongText,
      textColorDisabled: quietText,
      textColorText: strongText,
      textColorTextHover: strongText,
      textColorTextPressed: strongText,
      textColorTextFocus: strongText,
      textColorTextDisabled: quietText,
      textColorGhost: strongText,
      textColorGhostHover: strongText,
      textColorGhostPressed: strongText,
      textColorGhostFocus: strongText,
      textColorGhostDisabled: quietText,
      border: border,
      borderHover: borderHover,
      borderPressed: borderFocus,
      borderFocus: borderFocus,
      borderDisabled: borderDisabled,
      fontWeightStrong: "600",
    },
    Input: {
      borderRadius: "16px",
      color: isDark ? "rgba(15, 23, 42, 0.92)" : "rgba(255,255,255,0.96)",
      colorFocus: isDark ? "rgba(15, 23, 42, 0.96)" : "#ffffff",
      colorDisabled: subtleSurfaceDisabled,
      textColor: bodyText,
      textColorDisabled: quietText,
      placeholderColor: quietText,
      placeholderColorDisabled: quietText,
      caretColor: "#60a5fa",
      iconColor: quietText,
      iconColorHover: mutedText,
      iconColorPressed: strongText,
      clearColor: quietText,
      clearColorHover: mutedText,
      clearColorPressed: strongText,
      countTextColor: quietText,
      countTextColorDisabled: quietText,
      groupLabelColor: subtleSurface,
      groupLabelTextColor: mutedText,
      suffixTextColor: mutedText,
      border: border,
      borderHover: borderHover,
      borderDisabled: borderDisabled,
      borderFocus: borderFocus,
      boxShadowFocus: focusRing,
    },
    Select: {
      borderRadius: "16px",
      color: isDark ? "rgba(15, 23, 42, 0.92)" : "rgba(255,255,255,0.96)",
      colorActive: isDark ? "rgba(15, 23, 42, 0.96)" : "#ffffff",
      colorDisabled: subtleSurfaceDisabled,
      textColor: bodyText,
      placeholderColor: quietText,
      arrowColor: quietText,
      arrowColorDisabled: quietText,
      clearColor: quietText,
      clearColorHover: mutedText,
      clearColorPressed: strongText,
      border: border,
      borderHover: borderHover,
      borderActive: borderFocus,
      menuBoxShadow: isDark ? "0 24px 60px rgba(2, 6, 23, 0.5)" : "0 18px 42px rgba(15, 23, 42, 0.12)",
    },
    Card: {
      borderRadius: "24px",
      paddingSmall: "16px",
      paddingMedium: "20px",
      paddingLarge: "24px",
      color: isDark ? "rgba(10, 18, 30, 0.72)" : "rgba(255,255,255,0.76)",
    },
    Tabs: {
      colorSegment: isDark ? "rgba(15, 23, 42, 0.86)" : "rgba(255, 255, 255, 0.8)",
      tabColorSegment: isDark ? "rgba(30, 41, 59, 0.94)" : "rgba(255, 255, 255, 0.98)",
      tabTextColorSegment: quietText,
      tabTextColorActiveSegment: strongText,
      tabTextColorHoverSegment: strongText,
      tabTextColorDisabledSegment: isDark ? "rgba(148, 163, 184, 0.52)" : "rgba(100, 116, 139, 0.5)",
      paneTextColor: bodyText,
      barColor: "#2563eb",
      tabFontWeight: "500",
      tabFontWeightActive: "600",
      tabBorderRadius: "16px",
      panePaddingSmall: "12px 0 0 0",
      panePaddingMedium: "14px 0 0 0",
      panePaddingLarge: "16px 0 0 0",
    },
    Drawer: {
      borderRadius: "28px",
      color: panelColor,
    },
    Form: {
      labelTextColor: strongText,
      feedbackTextColor: mutedText,
      feedbackTextColorError: "#f87171",
      feedbackTextColorWarning: "#fbbf24",
      labelFontWeight: "600",
    },
    Dialog: {
      color: panelColor,
      border: border,
      titleTextColor: strongText,
      textColor: mutedText,
      closeIconColor: quietText,
      closeIconColorHover: strongText,
      closeIconColorPressed: strongText,
      closeColorHover: subtleSurface,
      closeColorPressed: subtleSurfaceHover,
      borderRadius: "24px",
      closeBorderRadius: "14px",
    },
    Dropdown: {
      borderRadius: "18px",
      color: floatingColor,
      dividerColor: isDark ? "rgba(148, 163, 184, 0.14)" : "rgba(15, 23, 42, 0.08)",
      optionTextColor: bodyText,
      optionTextColorHover: strongText,
      optionTextColorActive: strongText,
      optionColorHover: subtleSurface,
      optionColorActive: subtleSurfaceHover,
      groupHeaderTextColor: quietText,
      suffixColor: quietText,
      prefixColor: quietText,
    },
    Popover: {
      borderRadius: "18px",
      color: floatingColor,
      textColor: bodyText,
      dividerColor: isDark ? "rgba(148, 163, 184, 0.14)" : "rgba(15, 23, 42, 0.08)",
      boxShadow: isDark ? "0 24px 60px rgba(2, 6, 23, 0.5)" : "0 18px 42px rgba(15, 23, 42, 0.12)",
    },
    Alert: {
      borderRadius: "18px",
      color: isDark ? "rgba(15, 23, 42, 0.88)" : "rgba(255,255,255,0.82)",
      titleTextColor: strongText,
      contentTextColor: mutedText,
      colorInfo: isDark ? "rgba(30, 41, 59, 0.92)" : "rgba(239, 246, 255, 0.98)",
      colorSuccess: isDark ? "rgba(6, 78, 59, 0.42)" : "rgba(236, 253, 245, 0.98)",
      colorWarning: isDark ? "rgba(120, 53, 15, 0.42)" : "rgba(255, 247, 237, 0.98)",
      colorError: isDark ? "rgba(127, 29, 29, 0.42)" : "rgba(254, 242, 242, 0.98)",
    },
    Empty: {
      textColor: mutedText,
      extraTextColor: quietText,
      iconColor: quietText,
    },
    Switch: {
      iconColor: isDark ? "#0f172a" : "#ffffff",
      textColor: bodyText,
      railColor: isDark ? "rgba(51, 65, 85, 0.92)" : "rgba(203, 213, 225, 0.9)",
      railColorActive: "#2563eb",
      buttonColor: isDark ? "#e2e8f0" : "#ffffff",
      buttonBoxShadow: isDark ? "0 10px 20px rgba(2, 6, 23, 0.28)" : "0 8px 18px rgba(15, 23, 42, 0.12)",
      boxShadowFocus: isDark ? "0 0 0 3px rgba(59,130,246,0.2)" : "0 0 0 3px rgba(59,130,246,0.12)",
      railBorderRadiusSmall: "999px",
      railBorderRadiusMedium: "999px",
      railBorderRadiusLarge: "999px",
      buttonBorderRadiusSmall: "999px",
      buttonBorderRadiusMedium: "999px",
      buttonBorderRadiusLarge: "999px",
    },
    Log: {
      loaderTextColor: mutedText,
      loaderColor: "#2563eb",
      loadingColor: "#2563eb",
      loaderBorder: isDark ? "1px solid rgba(148,163,184,0.18)" : "1px solid rgba(148,163,184,0.25)",
    },
    Progress: {
      railColor: isDark ? "rgba(51, 65, 85, 0.92)" : "rgba(226, 232, 240, 0.96)",
      fillColor: "#0ea5e9",
      fillColorInfo: "#0ea5e9",
      fillColorSuccess: "#10b981",
      fillColorWarning: "#f59e0b",
      fillColorError: "#ef4444",
      textColorLineOuter: mutedText,
      textColorLineInner: "#eff6ff",
      lineBgProcessing: isDark ? "rgba(125, 211, 252, 0.24)" : "rgba(125, 211, 252, 0.22)",
    },
    Spin: {
      color: "#0ea5e9",
      textColor: mutedText,
      opacitySpinning: "0.72",
    },
    Pagination: {
      itemBorderRadius: "14px",
      buttonBorderRadius: "14px",
      buttonColor: subtleSurface,
      buttonColorHover: subtleSurfaceHover,
      buttonColorPressed: subtleSurfacePressed,
      buttonBorder: border,
      buttonBorderHover: borderHover,
      buttonBorderPressed: borderFocus,
      buttonIconColor: strongText,
      buttonIconColorHover: strongText,
      buttonIconColorPressed: strongText,
      itemTextColor: strongText,
      itemTextColorHover: strongText,
      itemTextColorPressed: strongText,
      itemTextColorActive: strongText,
      itemTextColorDisabled: quietText,
      itemColor: subtleSurface,
      itemColorHover: subtleSurfaceHover,
      itemColorPressed: subtleSurfacePressed,
      itemColorActive: isDark ? "rgba(56, 189, 248, 0.18)" : "rgba(14, 165, 233, 0.14)",
      itemColorActiveHover: isDark ? "rgba(56, 189, 248, 0.24)" : "rgba(14, 165, 233, 0.2)",
      itemColorDisabled: subtleSurfaceDisabled,
      itemBorder: border,
      itemBorderHover: borderHover,
      itemBorderPressed: borderFocus,
      itemBorderActive: isDark ? "1px solid rgba(125,211,252,0.46)" : "1px solid rgba(14,165,233,0.3)",
      itemBorderDisabled: borderDisabled,
      jumperTextColor: mutedText,
      jumperTextColorDisabled: quietText,
    },
    Upload: {
      borderRadius: "20px",
      draggerColor: isDark ? "rgba(15, 23, 42, 0.88)" : "rgba(255, 255, 255, 0.86)",
      draggerBorder: border,
      draggerBorderHover: borderHover,
      itemColorHover: subtleSurface,
      itemColorHoverError: isDark ? "rgba(127, 29, 29, 0.28)" : "rgba(254, 226, 226, 0.88)",
      itemTextColor: bodyText,
      itemTextColorError: isDark ? "#fda4af" : "#dc2626",
      itemTextColorSuccess: isDark ? "#6ee7b7" : "#059669",
      itemIconColor: quietText,
      itemBorderImageCard: border,
      itemBorderImageCardError: isDark ? "1px solid rgba(248,113,113,0.36)" : "1px solid rgba(239,68,68,0.28)",
    },
    Message: {
      borderRadius: "18px",
      color: floatingColor,
      colorInfo: floatingColor,
      colorSuccess: floatingColor,
      colorWarning: floatingColor,
      colorError: floatingColor,
      colorLoading: floatingColor,
      textColor: bodyText,
      textColorInfo: bodyText,
      textColorSuccess: bodyText,
      textColorWarning: bodyText,
      textColorError: bodyText,
      textColorLoading: bodyText,
      iconColor: quietText,
      closeBorderRadius: "12px",
      closeColorHover: subtleSurface,
      closeColorPressed: subtleSurfaceHover,
      closeIconColor: quietText,
      closeIconColorHover: strongText,
      closeIconColorPressed: strongText,
      boxShadow: isDark ? "0 24px 60px rgba(2, 6, 23, 0.46)" : "0 18px 42px rgba(15, 23, 42, 0.12)",
      boxShadowInfo: isDark ? "0 24px 60px rgba(2, 6, 23, 0.46)" : "0 18px 42px rgba(15, 23, 42, 0.12)",
      boxShadowSuccess: isDark ? "0 24px 60px rgba(2, 6, 23, 0.46)" : "0 18px 42px rgba(15, 23, 42, 0.12)",
      boxShadowWarning: isDark ? "0 24px 60px rgba(2, 6, 23, 0.46)" : "0 18px 42px rgba(15, 23, 42, 0.12)",
      boxShadowError: isDark ? "0 24px 60px rgba(2, 6, 23, 0.46)" : "0 18px 42px rgba(15, 23, 42, 0.12)",
      boxShadowLoading: isDark ? "0 24px 60px rgba(2, 6, 23, 0.46)" : "0 18px 42px rgba(15, 23, 42, 0.12)",
    },
    Notification: {
      borderRadius: "22px",
      color: floatingColor,
      textColor: bodyText,
      headerTextColor: strongText,
      descriptionTextColor: mutedText,
      actionTextColor: strongText,
      iconColor: quietText,
      closeBorderRadius: "12px",
      closeColorHover: subtleSurface,
      closeColorPressed: subtleSurfaceHover,
      closeIconColor: quietText,
      closeIconColorHover: strongText,
      closeIconColorPressed: strongText,
      boxShadow: isDark ? "0 24px 60px rgba(2, 6, 23, 0.5)" : "0 18px 42px rgba(15, 23, 42, 0.12)",
    },
    Tag: {
      borderRadius: "999px",
    },
    Checkbox: {
      borderRadius: "8px",
      color: isDark ? "rgba(15, 23, 42, 0.92)" : "#ffffff",
      colorChecked: "#2563eb",
      colorDisabled: subtleSurfaceDisabled,
      colorDisabledChecked: isDark ? "rgba(59, 130, 246, 0.46)" : "rgba(59, 130, 246, 0.34)",
      checkMarkColor: "#ffffff",
      checkMarkColorDisabled: quietText,
      checkMarkColorDisabledChecked: "#ffffff",
      border: border,
      borderDisabled: borderDisabled,
      borderDisabledChecked: borderDisabled,
      borderChecked: "1px solid #2563eb",
      borderFocus: borderFocus,
      boxShadowFocus: focusRing,
      textColor: bodyText,
      textColorDisabled: quietText,
    },
    DataTable: {
      borderRadius: "20px",
    },
  } as GlobalThemeOverrides;
}
